package one.yago.sorchat.protocol

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/** Wire protocol shared by the server and the Android app. */

val ProtocolJson = Json {
    ignoreUnknownKeys = true
    classDiscriminator = "type"
}

// ---- HTTP ----

@Serializable
data class RegisterRequest(val name: String)

@Serializable
data class RegisterResponse(val userId: String, val token: String)

@Serializable
data class UserInfo(val id: String, val name: String)

// ---- WebSocket ----

/** Frames sent from a client to the server. */
@Serializable
sealed interface ClientFrame {
    /**
     * Send a message. [id] is generated by the client so retries are idempotent:
     * the server ignores a message id it has already stored.
     */
    @Serializable
    @SerialName("send")
    data class Send(val id: String, val to: String, val body: String) : ClientFrame

    /** Confirms receipt of a message; the server then deletes it from its queue. */
    @Serializable
    @SerialName("ack")
    data class Ack(val id: String) : ClientFrame
}

/** Frames sent from the server to a client. */
@Serializable
sealed interface ServerFrame {
    /** The server has durably stored a message the client sent. */
    @Serializable
    @SerialName("accepted")
    data class Accepted(val id: String) : ServerFrame

    /** An incoming message. May be redelivered until acked, so clients must dedupe by [id]. */
    @Serializable
    @SerialName("message")
    data class Message(
        val id: String,
        val from: String,
        val fromName: String,
        val body: String,
        val sentAt: Long,
    ) : ServerFrame

    @Serializable
    @SerialName("error")
    data class Error(val id: String?, val reason: String) : ServerFrame
}
