package one.yago.sorchat.protocol

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/** Wire protocol shared by the server and the Android app. */

val ProtocolJson = Json {
    ignoreUnknownKeys = true
    classDiscriminator = "type"
}

// ---- HTTP ----

@Serializable
data class RegisterRequest(val name: String)

@Serializable
data class RegisterResponse(val userId: String, val token: String)

@Serializable
data class UserInfo(val id: String, val name: String)

/**
 * WebAuthn options for a passkey ceremony, as JSON to hand to Android's Credential Manager
 * unchanged. [requestId] ties the response back to these options.
 */
@Serializable
data class PasskeyOptions(val requestId: String, val optionsJson: String)

/** The Credential Manager's response JSON for a [PasskeyOptions] request. */
@Serializable
data class PasskeyResponse(val requestId: String, val responseJson: String)

/** A successful passkey sign-in: a fresh token for the account. */
@Serializable
data class LoginResponse(val userId: String, val name: String, val token: String)

/** Response to `POST /media`: the id to reference the upload by in a message's [Attachment]. */
@Serializable
data class UploadResponse(val mediaId: String)

/**
 * A file sent along with a message, uploaded beforehand through `POST /media`. The recipient
 * downloads it with `GET /media/{id}` and then confirms with `DELETE /media/{id}`, which frees
 * it on the server.
 */
@Serializable
data class Attachment(
    val mediaId: String,
    val mimeType: String,
    val size: Long,
    /** For audio and video. */
    val durationMs: Long? = null,
    /** Original file name, for files. */
    val name: String? = null,
    /** For images (and video): pixel size, so the chat can lay it out before it's downloaded. */
    val width: Int? = null,
    val height: Int? = null,
)

/** STUN/TURN servers for WebRTC, from `GET /ice-servers`. TURN credentials are short-lived. */
@Serializable
data class IceServer(val urls: List<String>, val username: String? = null, val credential: String? = null)

@Serializable
data class IceServersResponse(val servers: List<IceServer>)

/** WebRTC call setup, relayed between two connected users. Never stored by the server. */
@Serializable
sealed interface CallSignal {
    /** Starts a call. [sdp] is the caller's offer. */
    @Serializable
    @SerialName("invite")
    data class Invite(val sdp: String, val video: Boolean = false) : CallSignal

    /** The callee picked up. [sdp] is their answer. */
    @Serializable
    @SerialName("accept")
    data class Accept(val sdp: String) : CallSignal

    @Serializable
    @SerialName("ice")
    data class Ice(val sdpMid: String?, val sdpMLineIndex: Int, val candidate: String) : CallSignal

    @Serializable
    @SerialName("end")
    data class End(val reason: EndReason) : CallSignal
}

@Serializable
enum class EndReason {
    @SerialName("hangup") HANGUP,
    @SerialName("declined") DECLINED,
    @SerialName("busy") BUSY,
    /** The callee isn't connected. */
    @SerialName("unavailable") UNAVAILABLE,
    @SerialName("failed") FAILED,
}

/** Registers the device's FCM token so the server can wake it when messages are waiting. */
@Serializable
data class PushTokenRequest(val token: String)

// ---- WebSocket ----

/** Frames sent from a client to the server. */
@Serializable
sealed interface ClientFrame {
    /**
     * Send a message. [id] is generated by the client so retries are idempotent:
     * the server ignores a message id it has already stored.
     */
    @Serializable
    @SerialName("send")
    data class Send(
        val id: String,
        val to: String,
        val body: String,
        val attachment: Attachment? = null,
    ) : ClientFrame

    /** A call signal for [to], forwarded only if they're connected. */
    @Serializable
    @SerialName("call")
    data class Call(val to: String, val callId: String, val signal: CallSignal) : ClientFrame

    /** Confirms receipt of a message; the server then deletes it from its queue. */
    @Serializable
    @SerialName("ack")
    data class Ack(val id: String) : ClientFrame
}

/** Frames sent from the server to a client. */
@Serializable
sealed interface ServerFrame {
    /** The server has durably stored a message the client sent. */
    @Serializable
    @SerialName("accepted")
    data class Accepted(val id: String) : ServerFrame

    /** An incoming message. May be redelivered until acked, so clients must dedupe by [id]. */
    @Serializable
    @SerialName("message")
    data class Message(
        val id: String,
        val from: String,
        val fromName: String,
        val body: String,
        val sentAt: Long,
        val attachment: Attachment? = null,
    ) : ServerFrame

    @Serializable
    @SerialName("call")
    data class Call(val from: String, val fromName: String, val callId: String, val signal: CallSignal) : ServerFrame

    /** All messages queued while the client was offline have been sent. */
    @Serializable
    @SerialName("synced")
    data object Synced : ServerFrame

    @Serializable
    @SerialName("error")
    data class Error(val id: String?, val reason: String) : ServerFrame
}
